### ISSUE TITLE
Alexa doesnt say anything until i activate custom actions manually

### ISSUE THREAD

**Issue by supremelucifer** [keatontaylor/alexa-actions#114] opened 2022-07-15 20:31 UTC
I got to the very last step to test it but alexa doesnt ask "Should i turn off the lights?" when i press call service. However, when is say "Alexa, open custom actions, alexa will give me the question. When i put in a automation, it doesnt give me the question after the trigger but again, when i say "Alexa, open custom actions" Alexa asks the question. When i give the follow up Yes answer it will trigger my 2nd automation. Does anybody have a idea what i did wrong? Im using nabu casa for account linking

This is my call service after a trigger:

![image](https://user-images.githubusercontent.com/70238544/179305941-8f06855e-b8c2-48f7-901b-aeea6a8b2508.png)

This is my script:
![image](https://user-images.githubusercontent.com/70238544/179306179-515f87f4-7977-49c8-beca-1763b05fe5bb.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-15 21:32
Did you install [Alexa Media Player](https://github.com/custom-components/alexa_media_player/)?
That `alexa_device` doesn't seem right

**Comment by supremelucifer** [comment] 2022-07-15 21:36
Hi Deadsec-Security! Thank you for the response! I installed this custom component in Hacs. I assume its the right one?

![image](https://user-images.githubusercontent.com/70238544/179314308-dd064c27-8535-4e1e-a5b2-fd7b81380b24.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-15 21:40
Is the skill id that you put in the script correct?
Should be of this format: `amzn1.ask.skill.87fb0d7f-dddd-dddd-dddd-ddddddddd `

**Comment by supremelucifer** [comment] 2022-07-15 21:42
Yes, i believe so. I copied it straight from the developer console:

![image](https://user-images.githubusercontent.com/70238544/179314850-77189c7a-7161-4cb7-9a78-0c3d1af5bc55.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-15 21:54
Can you share the skill logs from cloud watch?

**Comment by supremelucifer** [comment] 2022-07-15 22:01
Am i on the correct page?

![image](https://user-images.githubusercontent.com/70238544/179316803-66e6e234-e42d-4005-bf6a-e3afac74a0d6.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-15 23:16
Yup, just select the last log stream

**Comment by supremelucifer** [comment] 2022-07-15 23:48
`This is what i got. Really appreciate the help! 

![image](https://user-images.githubusercontent.com/70238544/179325219-eb4b8d8d-9a6d-4c48-8fad-6f4cb7b06d1c.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-15 23:50
You have to activate debug mode. Can you switch the variable debug in the lambda function to True? That should do the work and then send me the logs again?

**Comment by supremelucifer** [comment] 2022-07-15 23:56
![image](https://user-images.githubusercontent.com/70238544/179325605-cd0d3d06-765d-4907-883c-b1f6b9fe783e.png)

I put it on, saved it and deployed to be sure but i feel like its the same. 

![image](https://user-images.githubusercontent.com/70238544/179325661-b8120a20-84fa-4c26-8384-81cec885a37d.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 00:05
Thats the old logs, you need to go back one page and select the new log group. Also you might need to trigger something so something actually appears in the logs. Try running you automation and then sending the logs.

**Comment by supremelucifer** [comment] 2022-07-16 00:15
![image](https://user-images.githubusercontent.com/70238544/179326542-4e2c5ce2-ba91-415c-b862-c38609a3c912.png)
![image](https://user-images.githubusercontent.com/70238544/179326556-5b065a25-c49e-4fc6-b87d-2ea0fefb634c.png)

This is the latest now. It appeard after i ask alexa "Open custom actions"

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 00:33
Are you using your account with admin privs for this?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 00:34
And in your home assistant config are you using double or single quotes in the json?

**Comment by supremelucifer** [comment] 2022-07-16 00:36
> And in your home assistant config are you using double or single quotes in the json?

Im using double qoutes in my config

**Comment by supremelucifer** [comment] 2022-07-16 00:37
> Are you using your account with admin privs for this?

Could you tell me how i can see this?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 00:39
> > And in your home assistant config are you using double or single quotes in the json?
> 
> Im using double qoutes in my config

Can you share a screen shot?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 00:40
> > Are you using your account with admin privs for this?
> 
> Could you tell me how i can see this?

When you logged in in the alexa skill did you use a new account just for the skill or your login creds?

**Comment by supremelucifer** [comment] 2022-07-16 00:42
> > > Are you using your account with admin privs for this?
> > 
> > 
> > Could you tell me how i can see this?
> 
> When you logged in in the alexa skill did you use a new account just for the skill or your login creds?

I used my own account. The same as where my echo is registered

**Comment by supremelucifer** [comment] 2022-07-16 00:42
This is my config:

![image](https://user-images.githubusercontent.com/70238544/179327524-b737375d-7d69-439b-b375-67fbba05fcee.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 01:18
When did you install this? Today?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 01:19
Can you try using `data:` instead of `data_template:`?

**Comment by supremelucifer** [comment] 2022-07-16 05:46
> Can you try using `data:` instead of `data_template:`?

I changed it but it still is the same. I installed it yesterday :)

**Comment by AxelWortmann** [comment] 2022-07-16 07:01
I´ve got the same issue and the same logs since a few weeks. Using the notification script suddenly Alexa does not say anything since May2022. Only if I say "Alexa, open cutom actions" the response is the text from the last triggered script activation. 
From End of 2021 everything worked fine. In the meantime I´v change the whole installation an have tested it with older HA core an alexa media player versions. 
Can it be an issue caused by Amazon Europe?
On the other hand the "Amazon Alexa Smart Home Skill" works until now without any problems.

**Comment by AxelWortmann** [comment] 2022-07-16 07:05
I´ve got the same issue and the same logs since a few weeks. Using the notification script suddenly Alexa does not say anything since May2022. Only if I say "Alexa, open cutom actions" the response is the text from the last triggered script activation.
From End of 2021 everything worked fine. In the meantime I´v change the whole installation an have tested it with older HA core an alexa media player versions.
Can it be an issue caused by Amazon Europe?
On the other hand the "Amazon Alexa Smart Home Skill" works until now without any problems.

**Comment by SAHWO** [comment] 2022-07-16 07:10
I´ve got the same issue and the same logs since a few weeks. Using the notification script suddenly Alexa does not say anything since May2022. Only if I say "Alexa, open cutom actions" the response is the text from the last triggered script activation.
From End of 2021 everything worked fine. In the meantime I´v change the whole installation an have tested it with older HA core an alexa media player versions.
Can it be an issue caused by Amazon Europe?
On the other hand the "Amazon Alexa Smart Home Skill" works until now without any problems.

**Comment by supremelucifer** [comment] 2022-07-16 10:17
Could it be the Alexa mediaplayer integration? It also won't let me make use of TTS.

**Comment by supremelucifer** [comment] 2022-07-16 11:24
Oh my fucking god, im a stupid cunt. In alexa mediaplayer you need to use amazon.de if you are in europe. I changed it and now it seems to work

**Comment by SAHWO** [comment] 2022-07-16 12:03
I´m using amazon.de already but it does not work.

**Comment by supremelucifer** [comment] 2022-07-16 12:43
> I´m using amazon.de already but it does not work.

Is TTS working for you? And can you change te volume of your echo in hassio? Before i changed to .de this was not possible

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 13:59
Can I close this issue @supremelucifer ?

**Comment by supremelucifer** [comment] 2022-07-16 14:43
As for me yes! I don't know if  Sahwo needs more help. Thanks for all the help!

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 14:44
@SAHWO if you need help regarding configs talk to me at discord https://discord.gg/dvmeuDaypk

**Comment by SAHWO** [comment] 2022-07-16 18:54
> > I´m using amazon.de already but it does not work.
> 
> Is TTS working for you? And can you change te volume of your echo in hassio? Before i changed to .de this was not possible

I can change volume. TTS is not working. Type: anounce works e.g. with the HACS "mini-media-player"
@DEADSEC-SECURITY Sorry for the delay. Is it possible to open the issue again?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 19:02
@SAHWO can you send logs, config etc too?

**Comment by SAHWO** [comment] 2022-07-16 20:14
At the moment my HA is reachable using DuckDNS with Nginx Proxy Manager with SSL and long live token.
I ´ve also tested it with account linking and tested with nabucasa.  
This is the cloudwatch log after calling "Alexa, open custom actions":
![cloud_watch](https://user-images.githubusercontent.com/109409187/179370351-1677445b-b427-44b3-914a-56cd4c0e53d6.PNG)

![lambda_function](https://user-images.githubusercontent.com/109409187/179370514-c2d2bf37-8ef6-46c5-9b9c-b50b57ab1104.PNG)

The notification script:

![script](https://user-images.githubusercontent.com/109409187/179370585-bf66622e-75f1-4313-916a-6aecccd58561.PNG)

The configuration.yaml:
![configuration](https://user-images.githubusercontent.com/109409187/179370608-b5685ce1-c369-4e57-800b-f659710989ad.PNG)

**Comment by SAHWO** [comment] 2022-07-16 20:16
I´m wondering about the location "Irland" at cloudwatch, because my Alexa location is Germany:
![image](https://user-images.githubusercontent.com/109409187/179370677-a7c4aad4-5c91-434a-b6ea-15a39adbc50c.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 20:28
Did you update the code recently? Can you also share logs when you trigger the script to ask something?

**Comment by SAHWO** [comment] 2022-07-16 21:11
Yes, the code is updated recently. I tried the new versions of the alexa-actions codes published the last days.
If I trigger the script there is no log initialized at cloudwatch. Only if I say "Alexa, open custom actions"

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 21:32
Can you revert to older versions of the code? The code under master is buggy hasnt been tested

**Comment by SAHWO** [comment] 2022-07-17 07:13
I have revert all lambda codes to alexa-actions-0.8.1. But it is the same issue.

**Comment by SAHWO** [comment] 2022-07-17 07:31
Now I have activated the Debug-Mode. If I trigger the script again no log is generated. If I say "Alexa, open custom actions" this log is generated - and that is very different from the log of the newer version of the code.  
![image](https://user-images.githubusercontent.com/109409187/179388522-6ae22d4d-f5fe-47d5-8636-75b5812a0055.png)

**Comment by supremelucifer** [comment] 2022-07-17 08:06
> I´m wondering about the location "Irland" at cloudwatch, because my Alexa location is Germany: ![image](https://user-images.githubusercontent.com/109409187/179370677-a7c4aad4-5c91-434a-b6ea-15a39adbc50c.png)

I also got Ireland and still getting it so that shouldnt be the problem.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 13:25
> Now I have activated the Debug-Mode. If I trigger the script again no log is generated. If I say "Alexa, open custom actions" this log is generated - and that is very different from the log of the newer version of the code. ![image](https://user-images.githubusercontent.com/109409187/179388522-6ae22d4d-f5fe-47d5-8636-75b5812a0055.png)

That sounds like your script is not properly calling the skill can you double check the device entity id, skill id? And also that media player is properly set up

**Comment by SAHWO** [comment] 2022-07-17 15:35
> That sounds like your script is not properly calling the skill can you double check the device entity id, skill id? And also that media player is properly set up

I think that can be the problem. But I´ve checked the skill ID several times, with double and single quotes and without quotes. I´m using the same device entety ID as the mini media player which is working. The media Player is connected with amazon.de and is using 2FA. 
Some threads points out, if HA is reachable without Port :8123 the skill should not use long live token but account linking.  I´ve tried that too, because my firewall is routing the ports 80, 81 and 443 directly to HA and the nginx proxy manager administrates the ssl certificates. 
To exclude this as reason, I´ve booked the NabuCasa one month trial account. - Without success. 
To find the issue seems impossible for me meanwhile.
Thank you very much for the help.
Can I be sure if the "alexa open custom actions" command works, the skill is bidirectional connected correct?
Can I debug the notification script?  
The trace function is not detailed enough: 
![trace](https://user-images.githubusercontent.com/109409187/179405359-08cc8cc2-360c-4b42-bf2c-8d3a9f0056da.PNG)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 15:40
Is media_player configured correctly? In the dev tools can you manually trigger media_player to do something with that device?

**Comment by SAHWO** [comment] 2022-07-17 15:45
Only the Type: announce
Type: TTS does not work

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 15:47
Ok so media_player is working. 
Is media player using the right country?

**Comment by SAHWO** [comment] 2022-07-17 15:49
I hope so - My Alexa/Amazon account ist Germany and so I connected media player with amazon.de.
That should be correct.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 15:51
Have you tried remaking the skill?
Also if you're using long lived tokens could you try using a different HA account to generate the token?
If your using login could you try to login using a different account in HA?
Can you try reconnecting your media_player?

**Comment by SAHWO** [comment] 2022-07-17 15:57
OK - that I will try. I´m using only one HA user as administrator.
So I will generate one extra "Alexa" user. What permissions are necessary? Should it be an administrator?
Yes, I´ve remaked the skill already four times.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 16:13
Try different permissions, some users had problems when the account was admin though

**Comment by SAHWO** [comment] 2022-07-17 16:45
It becomes more crazy...
New user - new long live token - implemented at lambda_function.py
New user tested with login 
Result: notification script still not works - if calling "alexa open custom actions" alexa asks, but can not recognize my awnser and calls "ERROR_ACOUSTIC" - in German language ( Sorry I did not catch that...)
Also chaning the permission of that user:  without any success.
If I change the token to the previous user it works as previously. That makes no sense...I´m confused.

Now I will go back to a clear HA installation and will remake a skill. 
Schould I use the alexa-actions-0.8.1 ?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-18 01:12
yup

**Comment by AxelWortmann** [comment] 2022-07-18 19:09
Everything I´ve tried was unsuccessfull. 
Complete new HA installation, new alexa-media-player, new skill programming, new duckdns domain with ssl-certificates, reset of all alexa devices at amazon account.
Different HA user account with different permissions- with long live token and without. New firewall config with portforwarder without Nginx Proxy, 
Exactly always the same symptoms - the notification script does not work it seems that it does not call the skill.
Pobably I genarate always the same mistake. 
Debug logging of Alexa-media-player after calling the notification script is:

**Comment by AxelWortmann** [comment] 2022-07-18 19:16
2022-07-18 21:00:02 DEBUG (MainThread) [custom_components.alexa_media.media_player] a***********@*****e: <Entity Echo Sandra: standby>:Running skill amzn1.ask.skill.b13****-***-48b1-****-986******9fc with queue_delay 1.5
2022-07-18 21:00:03 DEBUG (MainThread) [alexapy.alexaapi] a***********@*****e: Creating sequence for 1 items
2022-07-18 21:00:03 DEBUG (MainThread) [alexapy.alexaapi] a***********@*****e: Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Operation.SkillConnections.Launch\", \"operationPayload\": {\"targetDevice\": {\"deviceType\": \"A7WX********\", \"deviceSerialNumber\": \"G090P3*****00\"}, \"locale\": \"de-de\", \"customerId\": \"A1S**********7\", \"connectionRequest\": {\"uri\": \"connection://AMAZON.Launch/amzn1.ask.skill.b13****-***-48b1-****-986******9fc\", \"input\": {}}}}]}}", "status": "ENABLED"}
2022-07-18 21:00:03 DEBUG (MainThread) [alexapy.alexaapi] a***********@*****e: POST: https://alexa.amazon.de/api/behaviors/preview returned 200:OK:application/octet-stream

**Comment by DEADSEC-SECURITY** [comment] 2022-07-19 18:04
Did you add/activate your skil in the alexa app?

**Comment by SAHWO** [comment] 2022-07-19 20:59
Yes, I´ve setting up a new skill and the old skill is deleted at develloper console. And the new skill ist activated. The skill ID is updated at the notification script.

**Comment by SAHWO** [comment] 2022-07-20 17:45
Yes, I think the problem is the call of the skill. 
This ist working:
![image](https://user-images.githubusercontent.com/109409187/180045480-eae5d299-3523-499f-acf3-c6f2c5bfd527.png)

And this too: 
![image](https://user-images.githubusercontent.com/109409187/180045670-fa240622-dc71-4c0a-836c-1ba67f2a98f0.png)

I´ve tried to trigger Common Skills - as described as examples at the manual of the alexa media player.
But I don´t know whether these skills will work at location DE - Germany


![image](https://user-images.githubusercontent.com/109409187/180047407-67c5bb67-1a12-4bc9-8b0e-b433254be046.png)


It would be helpfull, if I could get an info, wether the notification stills works in Germany. Perhaps there is a change at Amazon Germany guidelines.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-20 18:45
It should work, there is no reason it shouldn't but again the skill was only really tested on English

**Comment by SAHWO** [comment] 2022-07-20 19:13
It does not work. This is my "test-automation" with the skill ID of the "Question of the day". The skill is not installed at my alexa app because I can only find and activate German skills. But I think also,  it should work - but it doesn´t:

![image](https://user-images.githubusercontent.com/109409187/180063110-93606cba-46ae-4260-b828-0b6b7cc2f703.png)

**Comment by SAHWO** [comment] 2022-07-27 08:29
Now I have examined the alexa media player logs.
After restart of HA at first the login seems successfull:

![first](https://user-images.githubusercontent.com/109409187/181189716-2cfe21e1-eea7-4642-b454-0a926f3aa1ec.png)

After that a content type error occurred:

![second](https://user-images.githubusercontent.com/109409187/181191333-f9bf06ed-1366-42c6-a2b0-8b48fba433fa.png)

Then trigering the notification script:

![third](https://user-images.githubusercontent.com/109409187/181192142-a98d2615-ae8b-486f-9e65-ad6ed5e05551.PNG)

"returned 200:OK" seems successfull as response:

![image](https://user-images.githubusercontent.com/109409187/181193652-2c733176-0d74-40cc-a0e1-9df8f7672c1d.png)
https://developer.amazon.com/en-US/docs/alexa/account-linking/skill-activation-api.html

Interesting: The skill-ID at the script doesn´t matter. The logs are always the same. I´ve tried follwing at the script:
"media_content_id: XXXXXXXXXXX" and the log doesn´t change.

What´s about the endpoint setting at skill development? This is the default configuration and not changed by me. Or does it not matter because API is using?

![endpoint](https://user-images.githubusercontent.com/109409187/181197477-ae3fbeab-b064-48b8-86f9-05a845fe7f53.png)

Can the whole log be helpfull and should I post it?
Any idea to solve this problem?

**Comment by DEADSEC-SECURITY** [comment] 2022-07-28 00:13
Have you tried using a token instead of login?

**Comment by SAHWO** [comment] 2022-07-28 10:02
At lambda_function.py I´m using the token from a seperate user of HA:

![develop](https://user-images.githubusercontent.com/109409187/181476823-a222f43a-0e93-4999-98da-6dfa75436717.png)

And I´ve tested "account linking" also. 

The alexa_media_player is connected using the Built-In 2FA App:

![image](https://user-images.githubusercontent.com/109409187/181478083-33c8a27a-d3b4-4241-aaf3-dd31000b7e83.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-07-30 20:08
2FA might be the problem. Have you tried disabling 2FA?

**Comment by SAHWO** [comment] 2022-07-31 09:09
Where should I disable 2FA? Disabeling at my Amazon account or at the alexa_media_player credentials? How can I disable 2FA there? Should I leave the field "Built-in 2FA App Key" blank?
![image](https://user-images.githubusercontent.com/109409187/182019143-39a511c5-9fad-42af-ba4e-49e1109399c3.png)

**Comment by DEADSEC-SECURITY** [comment] 2022-08-01 00:25
Disable on your amazon account and media player so you dont have 2FA to login to amazon.

**Comment by SAHWO** [comment] 2022-08-01 19:40
Usally I´m testing with echo 2. generation. But I´ve tested also with my echo dot 4. generation, echo dot 2. generation and with echo flex. It´s really funny, because it had work with my echo 2. generation without any problems for several months until May 2022. 
After switch off the 2FA and reconnecting alexa_media_player all devices wer detected: 

![media_new](https://user-images.githubusercontent.com/109409187/182228855-d3baeb62-1d13-4a4b-9f4c-f1f7b5f15f64.PNG)

And I´m wondering about the skill connection. If I call the notification script there is no log entry at CloudWatch Logs. Only if I ask "Alexa open custom actions".
And why doesn´t it matter which Skill-ID I put into the notification script? Exen if I put in XXXXX. The logs stay the same.

**Comment by DEADSEC-SECURITY** [comment] 2022-08-01 19:56
Because you need to tell the media player which skill to run. The media player runs the skill!

**Comment by SAHWO** [comment] 2022-08-02 17:32
Yes, that´s right and the skill ID is set at the notification script:

![script_1](https://user-images.githubusercontent.com/109409187/182436970-d9e21f4c-21fd-4241-8d99-7bd37139253e.png)

Is there any other option to set the skill-ID ?
Can I check the functionality of triggering a skill?

**Comment by DEADSEC-SECURITY** [comment] 2022-08-03 12:24
`entity_id` try switching to single quotes.

**Comment by SAHWO** [comment] 2022-08-03 13:19
Unfortunately no change - and the logs stay the same.
I´ve tried also double quotes at media_content_id.

**Comment by DEADSEC-SECURITY** [comment] 2022-08-03 13:43
Have you tried manually setting one device to play the skill see if that works?

**Comment by DEADSEC-SECURITY** [comment] 2022-08-04 01:20
Instead of `"{{ alexa_device }}"` put your device id `media_player.echo_<SOMETHING>`

**Comment by DEADSEC-SECURITY** [comment] 2022-08-04 01:21
On the dev tools you can call the service manually too

**Comment by SAHWO** [comment] 2022-08-06 06:52
I'm on vacation at the moment and will check this end of the next week.

**Comment by nukeKid** [comment] 2022-08-08 18:28
I apologize in advance for my bad english but maybe I can help you.

I had the same error and the solution was when logging in the alexa media player i had to check "keep me logged in" and "don't ask for 2FA in this browser again"

after that it worked

**Comment by SAHWO** [comment] 2022-08-21 19:05
I´ve solved the problem. At first it´s necessary to say:  Until May of 2022 the notification script worked perfect.
My family is using the Amazon "Households and Family Library" function. All Echos and Alexa devices are registered by my wife.
I´m registered at Amazon with my personal mail-adress and I´m using the second profile of the "Households and Family Library" funtionality and so I have access to all echo devices and Amazon content.
If I want to use it, I say to Alexa: "Change the profile" - then Alexa changes to my profile and the skills of my Alexa login are active.
Now I´ve ordered, connected and registered a new Echo Dot using my personal Amazon login and this Echo device now works fine with HA notification.
I don´t know wether the Amazon funtion "Households and Family Library" only exists in Germany or in other regions also. So I think the whole problem was caused by changing some rules by Amazon probably.
Thank you all for your support.  The issue can be closed.

**Comment by DEADSEC-SECURITY** [comment] 2022-08-24 13:25
Good to know

**Closed by DEADSEC-SECURITY** 2022-08-24 13:25 UTC
