### ISSUE TITLE
Anomaly: lambda function stopped picking up update values

### ISSUE THREAD

**Issue by paoloantinori** [keatontaylor/alexa-actions#75] opened 2021-01-22 17:31 UTC
I'm not really sure what I have observed here, but I'm posting it here if it can help someone else:

Lambda function stopped picking up updated values from the read of the input_text on HA.

I've attached a debugger with VSCode and I can notice that between multiple invocations, this check:

https://github.com/keatontaylor/alexa-actions/blob/ae3d9e43983462faacd11df31a3079db4f2201ea/lambda/lambda_function.py#L56

returned false, using the cached value instead of the correct changed one.

The fix has been simple, just commenting out the `if` statement.

Anyhow, I have no idea how come this has suddenly started appearing.

Might have AWS changed the lifecycle or memory assumption of the lambda and now I'm hitting a long-running lambda while I wasn't in the past?

No idea, but this fixed my problem.

**Comment by razorface1978** [comment] 2021-03-02 02:06
i tried that but i still get problem with the skills response

**Comment by seantunley** [comment] 2021-09-09 19:09
has anyone found out how to fix this issue? The input text is being cached and then remains the same for the automations

**Comment by dreimer1986** [comment] 2022-02-02 20:39
You are a god. I fought for days now to get along that problem. I even was so sure the flaw can not come from that few lines of Python that I asked over at the addon issue tracker. He closed my report which might have caused a not too friendly answer from my side. And now it's THIS....

https://github.com/keatontaylor/alexa-actions/issues/102

Now I just need to find out why the skill does persist on my Echo Show forever until I force close it by voice command.

**Comment by dreimer1986** [comment] 2022-06-26 12:19
Still recent. When I try my luck with 13222b138ab32a8556c6ebf07d79f87e4bf49da9 including my updated String handler I have always the same text outputted unless I comment out the new if statement (if not self.ha_state:) in line 75. If that is done all works fine again. Here in my sorry try to pass text answers to some sort of correspondence directly to HA. It shows the applied hack frm here and it works only that way. Maybe you are interested to add it yourself. ^^

**Comment by DEADSEC-SECURITY** [comment] 2022-07-10 14:45
For some reason it seems to be a bug in some devices. In my alexa works fine with it but some devices don't not sure why.

**Comment by dreimer1986** [comment] 2022-07-10 19:08
Sidenote. I try it with an Echo Show 7. Maybe that's the problem.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-10 20:19
That could be, did you manage to test with normal echos @dreimer1986.
Cuz we have a handler for Dates not sure if that device supports it though

**Comment by dreimer1986** [comment] 2022-07-11 09:11
Not yet, but can be done soon ish....

**Comment by DEADSEC-SECURITY** [comment] 2022-07-11 18:31
Ok let me know if you manage to get some useful information @dreimer1986. Highly appreciate the help.

**Comment by dreimer1986** [comment] 2022-07-12 17:50
OK, changed back my modifications and tested it on my Echo Dot today (I kept my string handler of course ^^). I confirm 100% reliability on it. Just changing back my automations to my Show causes the same problematic behavior again. So it's the Show making fuzz here indeed.

**Comment by dreimer1986** [comment] 2022-07-15 23:49
Well, in theory my pull does not fix the problem. ^^ Removing the if would do so. At least it fixes it for Echo Show users.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-16 14:49
Echo shows are known so far to not work properly with skills for some weird reason, one fix we could try to implement is to have a way to check what type of device is running the skill but I'll have to investigate. @dreimer1986 if you find anything that could help let me know :).

**Comment by dreimer1986** [comment] 2022-07-17 01:23
Line 78 + 79:

```
        if not self.ha_state:
            self.get_ha_state()
```

I changed it to

```
        self.get_ha_state()
```

So I did what @paoloantinori explains in the start of the report. It helps perfectly on the Echo Show, but I have no idea if the one has ANY negative side effects.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 01:55
I mean it shouldn't affect other devices but I can't test it right now. So if someone could give me some feedback. This seems to be the top issue right now so I might remove the if statement if it doesn't break for other devices.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-17 02:36
Could also be the fact that ha_state is class variable and could be causing issues in the lambda. Ill have to further test this possibility.

**Comment by paoloantinori** [comment] 2022-07-17 06:18
I can confirm that it was in a Show 7 that I was facing the issue. Interesting to hear it's a known fact they often are affected by anomalies.

**Comment by dreimer1986** [comment] 2022-07-20 17:14
https://github.com/keatontaylor/alexa-actions/commit/f3f151fba842bd3c275a464485f6f4f838991667 confirmed fix over here.

**Closed** 2022-07-20 18:46 UTC
Labels: bug, help wanted
