### ISSUE TITLE
Alexa doesn't make a sound when testing the input text

### ISSUE THREAD

**Issue by Shawn9347** [keatontaylor/alexa-actions#91] opened 2021-08-15 18:47 UTC
Hello, 

I have build the alexa skill and succesfully logged in to home assistant in the alexa app. I also have pasted the input text in my config.yaml. But for some reason when I say: "Alexa, open custom actions" it makes a brief sound and then goes back to sleep. Can anyone help me with this?

**Comment by Gnaj** [comment] 2021-08-18 10:16
hello ! did you manage to figure it out? i'm having the same issue

**Comment by formatBCE** [comment] 2021-08-18 21:45
+1 to this one. Seems like something broke recently.

**Comment by Rickexe** [comment] 2021-08-20 07:45
Hey, sorry for my late response. I haven't managed to fix it yet. I seems the owner is not that active so hopefully we'll get a fix soon.

**Comment by satyambaba** [comment] 2022-01-11 21:08
I am having the same issue.

**Comment by paulcusick3** [comment] 2022-01-19 15:28
Dead i guess????

**Comment by formatBCE** [comment] 2022-01-19 15:30
> Dead i guess????

I deleted it from my installation far ago...

**Comment by DEADSEC-SECURITY** [comment] 2022-07-10 14:30
Hey guys, I'm currently maintaining this repository, is this still an issue?

**Comment by Shawn9347** [comment] 2022-07-10 15:32
Presumably. Haven't tested it in ages. I would like to see it working, though.

**Comment by formatBCE** [comment] 2022-07-10 16:58
> Hey guys, I'm currently maintaining this repository, is this still an issue?

Well, it works for me.

**Comment by Shawn9347** [comment] 2022-07-10 17:41
Oh lol

**Comment by DEADSEC-SECURITY** [comment] 2022-07-10 20:18
Since there are no recent feedback on this and I cant reproduce I'm going to close the Issue

**Comment by Shawn9347** [comment] 2022-07-21 12:45
It's actually still not working. I just tried it again. I built the skill. Alexa still says: "sorry I don't know that".

**Comment by DEADSEC-SECURITY** [comment] 2022-07-21 18:43
Did you configure the skill in the app? @Shawn9347

**Comment by Shawn9347** [comment] 2022-07-21 18:53
Yes. Obviously.

**Comment by DEADSEC-SECURITY** [comment] 2022-07-21 19:41
Can you send me logs, HA config, skill config any other thing that might help trouble shoot the problem?

**Comment by Shawn9347** [comment] 2022-07-21 19:44
I will. Tomorrow. On mobile rn not home. Keep the issue opened.

**Comment by DiGiSoUL84** [comment] 2022-08-15 07:26
Just built everything but no response when saying "open custom actions"

**Comment by DEADSEC-SECURITY** [comment] 2022-08-15 19:43
Did you activate the skill? @DiGiSoUL84

**Comment by DiGiSoUL84** [comment] 2022-08-15 19:45
> Did you activate the skill? @DiGiSoUL84 

Yes I did but I think I have the language on the echo set to GB and configured the skill the US. Will confirm when I get home from work

**Comment by DiGiSoUL84** [comment] 2022-08-15 21:56
I had the language wrong soon as I changed it worked

**Comment by Shawn9347** [comment] 2022-08-16 18:50
Okay. I actually got it working now as well. However, I have to set it to "English (UK)" for it to work. I'm based in Europe but I still would like to have Alexa saying stuff with an American accent. How can I change the skill language to US without changing the region to US?

**Comment by DEADSEC-SECURITY** [comment] 2022-08-16 22:34
Unfortunately as far as I know that's on Amazons hands, you need to change the region to change the skill language.

**Closed by DEADSEC-SECURITY** 2022-08-16 22:34 UTC
Labels: bug
