### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by razorface1978** [keatontaylor/alexa-actions#78] opened 2021-02-27 06:36 UTC
this is all i get when i try to open custom actions

**Comment by barto95100** [comment] 2021-02-27 17:29
YEs I have the same error :(

**Comment by sandersc242** [comment] 2021-02-27 19:52
Same error :(

**Comment by davidhpayne** [comment] 2021-02-28 15:53
Same problem here too!

**Comment by sandersc242** [comment] 2021-02-28 19:06
> Same problem here too!

I just ended up using the Alexa media integration to execute routines and play music ect. Which surprisingly works really well so far

**Comment by davidhpayne** [comment] 2021-03-01 07:25
> > Same problem here too!
> 
> I just ended up using the Alexa media integration to execute routines and play music ect. Which surprisingly works really well so far

Can you get Alexa to ask questions for you to respond to with just the media player though? I thought you needed this as well for actionable notifications.

**Comment by sandersc242** [comment] 2021-03-01 13:10
> you

I intended to use it to trigger routines. Hopefully someone figures this out because actionable notifications would be useful

**Comment by razorface1978** [comment] 2021-03-02 01:56
i wonder if hes going to check this thread or just not support this anymore

**Comment by Bobbyiv** [comment] 2021-03-02 02:16
Please join discord with the below link. You will get help there.

https://discord.gg/qUErTEz2

**Comment by Bobbyiv** [comment] 2021-03-02 02:19
> i wonder if hes going to check this thread or just not support this anymore

Please join discord for help. Link will expires in 7 days. (2021/3/1 to 2021/3/8)

https://discord.gg/qUErTEz2

**Comment by Bobbyiv** [comment] 2021-03-02 02:19
> > you
> 
> I intended to use it to trigger routines. Hopefully someone figures this out because actionable notifications would be useful

Please join discord for help. Link will expires in 7 days. (2021/3/1 to 2021/3/8)

https://discord.gg/qUErTEz2

**Comment by razorface1978** [comment] 2021-03-02 02:33
Didn’t work bad invite

Sent from Mail for Windows 10

**Comment by keatontaylor** [comment] 2021-03-02 05:56
I think I need a bit more info to hopefully provide some help. Generally, you can always look into the CloudWatch logs for the lambda function to see what exactly is causing it to say that there was a problem with the requested skill's response and those might give me clues into the issues.

**Comment by davidhpayne** [comment] 2021-03-02 07:40
> I think I need a bit more info to hopefully provide some help. Generally, you can always look into the CloudWatch logs for the lambda function to see what exactly is causing it to say that there was a problem with the requested skill's response and those might give me clues into the issues.

Hi Keaton, I'm not familiar with the Cloudwatch logs. Is there something I need to do to view this on the AWS console? I was playing around on the test tab in the alexa developer console to try and find something more helpful to share. Is there something I should be looking for? The logs seem quite generic on there and just show me loads of code when I click on individual events. 
[7:39:01:055] - Event: System.SynchronizeState
[7:39:01:058] - Event: Alexa.SmartMotion.ModeChanged
[7:39:01:061] - Event: Settings.SettingsUpdated
[7:39:01:066] - Event: System.SynchronizeState
[7:39:01:070] - Event: System.SynchronizeState
[7:39:08:306] - Event: SpeechRecognizer.Recognize
[7:39:09:709] - Directive: SkillDebugger.CaptureDebuggingInfo
[7:39:09:768] - Directive: SkillDebugger.CaptureError
[7:39:09:913] - Directive: SkillDebugger.CaptureDebuggingInfo
[7:39:10:017] - Directive: SpeechRecognizer.RequestProcessingStarted
[7:39:10:020] - Directive: SpeechSynthesizer.Speak
[7:39:10:022] - Directive: CardRenderer.RenderCard
[7:39:10:026] - Directive: SpeechRecognizer.RequestProcessingCompleted
[7:39:10:093] - Event: SpeechSynthesizer.SpeechStarted
[7:39:10:162] - Directive: SkillDebugger.CaptureError
[7:39:10:168] - Directive: SkillDebugger.CaptureDebuggingInfo
[7:39:13:903] - Event: SpeechSynthesizer.SpeechFinished

**Comment by davidhpayne** [comment] 2021-03-03 15:40
I think the issue was with Alexa media player. I had it set as amazon.com instead of .co.uk
Alexa actions then needed me to set it up using the EU Client ID. I included English (UK) and English (US) in the languages just to be certain. It all works now!

**Comment by barto95100** [comment] 2021-03-03 15:55
@davidhpayne  how to configure this ? in alexa developper web page (client ID ?)

**Comment by davidhpayne** [comment] 2021-03-03 15:57
@barto95100  which bit are you wanting to configure? Just the Alexa actions or the media player too?

**Comment by davidhpayne** [comment] 2021-03-03 16:00
@barto95100 I used the EU client ID (I'm in the UK). I signed into my Alexa media player using amazon.co.uk though rather than amazon.com

**Comment by barto95100** [comment] 2021-03-04 08:34
@davidhpayne  Ok i'm in france, and I use the https://layla.amazon.com/ and don't work I have the this sound (in french language) 
There was a problem with the requested skill's response

**Comment by razorface1978** [comment] 2021-03-05 03:02
I found my problem it was the url in the lambda py file at the top you can't use quotes and it has to be right up next to the = sign then mine linked and worked so happy

**Comment by rklueber** [comment] 2021-03-06 09:48
Please check if you added the files `language_strings.json `and `prompt.py` at the right place. I find the Howto ambiguous at this particular point. Be sure NOT to put them in the subfolder lambda but in the main directory.

**Comment by sstratoti** [comment] 2021-03-11 18:25
Just wanted to add my experience. 

1. My issue was that I failed to create the [input_text entity](https://github.com/keatontaylor/alexa-actions/wiki/InitialConfig#creating-the-input_text-entity) from this page in my HomeAssistant environment.
2. I tried moving the files @rklueber mentioned under the main directory. This did not work. They worked under the lambda directory (as it appears in this repo). It's also prompts.py, not prompt.py.

HTH someone else!

**Comment by barto95100** [comment] 2021-03-12 12:06
the problem persist : 
 
This is my configuration skiil

Folder file skiil:
[https://ibb.co/MDKdPKp](url)

lambda_function.py:
[https://ibb.co/HdpLDjb](url)

language_strings.json:
[https://ibb.co/HdpLDjbhttps://ibb.co/r5TcfkT](url)

prompts.py:
[https://ibb.co/HdpLDjbhttps://ibb.co/r5TcfkThttps://ibb.co/DYnNTn1](url)

json:
[https://ibb.co/7v5vSyr](url)

Account linking:
[https://ibb.co/bddHVv9](url)

When I test to alexa to say: open custom skiil I have this : 
[https://ibb.co/7JfWrWb](url)

In developper alexa site, test tab:
[https://ibb.co/qMBxJHS](url)

and the response json format:

`{
	"version": "1.0",
	"session": {
		"new": true,
		"sessionId": "amzn1.echo-api.session.40b029ba-ca91-43ee-bd52-....2de49",
		"application": {
			"applicationId": "amzn1.ask.skill.44a10866-e47d-427a-a01f-9....b7f26a"
		},
		"user": {
			"userId": "amzn1.ask.account.AFWP7ZTNV5JD....EBBGGAIXJF44A",
			"accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1....aycRq4U3qQ"
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"mode": "HUB",
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		],
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"mode": "HUB",
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"Extensions": {
			"available": {
				"aplext:backstack:10": {}
			}
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.44a10866-e47d-427a-a01f-9738b8b7f26a"
			},
			"user": {
				"userId": "amzn1.ask.account.AFWP7ZTNV5JD2CVIVK5MH6F3HNG5W6IDTRGXUC2QWWWEBHAYWJNIWMQW4TTTHB62WB7SK5NHLXRDC4BMLDJKPGOPA....",
				"accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4N2MyMjM5ODAzZmQ0NWVmOThlNGQwNTdjYTk3N2U5YyIsImlhdCI6MTYxNTU1MDE1NiwiZXhwIjoxNjE1NTUxO...."
			},
			"device": {
				"deviceId": "amzn1.ask.device.AGVAS4LV5FGT6THQLEYBTCFSIEWGV66YGYN4PYEIVE4HEUGT7C3FXOICTGROZ4CTL2UO7YVEOZ3R7BI3.....",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5ldS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjQ0YTEwODY2LWU0N2QtNDI3YS1hMDFmLTk3MzhiOGI3ZjI2YSIsImV4cCI6MTYxNTU1MTAwMCwiaWF0IjoxNjE1NTUwNzAwLCJuYmYiOjE2MTU1NTA3MDAsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDaVMyeFRIeWpzellpRERPM2RVWDZCS2dFQUFBQUFBQUJLZERrcXJRQVpQVk00RVYwT1pyVm9OcG5JcUtFMkhvck1TQjZwVkJHY0I1azhqQUR6NlViQnVITXVRSWJ4MGdjK0Q0WHJsSlZoTEg2cno1ZkJQSEFLNGM3VXFnd0h1c1RRMFpBem95MmZHdGpDR3phU2ozMEFIQlZIQlpHT3hTSndZVjBoWmhjMzlnUnRFZkxzMW5ab2x1K3JacmNtVWhTVlpGU0hualJiNW1hekJyeDZCM0U4cjVzOGJnSmhmZl....."
		}
	},
	"request": {
		"type": "LaunchRequest",
		"requestId": "amzn1.echo-api.request.f352a3e0-0af5-4e31-9d56-24590c755804",
		"timestamp": "2021-03-12T12:05:02Z",
		"locale": "fr-FR",
		"shouldLinkResultBeReturned": false
	}
}`

**Comment by sstratoti** [comment] 2021-03-15 16:25
Did you create the input_text entity from [this page](https://github.com/keatontaylor/alexa-actions/wiki/InitialConfig#creating-the-input_text-entity) in the HomeAssistant environment?

Also, is the url at the top of your lambda_function referencing nabu casa, but the auth URL in you account linking looks a little different? Tough to say, they're both mostly blocked out.

**Comment by barto95100** [comment] 2021-03-15 18:05
> Did you create the input_text entity from [this page](https://github.com/keatontaylor/alexa-actions/wiki/InitialConfig#creating-the-input_text-entity) in the HomeAssistant environment?
> 
> Also, is the url at the top of your lambda_function referencing nabu casa, but the auth URL in you account linking looks a little different? Tough to say, they're both mostly blocked out.

YEs the url is the same now I test with url nabu casa and direct url DNS and the same 

I create the file input_text.yaml in my HA (packages)

[https://ibb.co/1ZXn2kv](url)

**Comment by sstratoti** [comment] 2021-03-15 18:29
The only other thing I see that's different is your language file. Looks like you're trying to set up French. Maybe try it with US first to make sure that the language isn't the issue? Process of elimination?

**Comment by barto95100** [comment] 2021-03-15 18:46
> ~ The only other thing I see that's different is your language file. Looks like you're trying to set up French. Maybe try it with US first to make sure that the language isn't the issue? Process of elimination? ~
> Nevermind, that probably wont work because...well...you're using FR servers. Just read up above.

I configure in gui DEv Alexa the url for US https://pitangui.amazon.com/ and in my integration HA I use the amazon.com

and the same problem :(

**Comment by EgoManiac** [comment] 2021-04-08 08:39
I had this problem.. It turned out that I had created the text_input entity, but I hadn't reloaded HomeAssistant. Bit of a "Doh!" moment for me.

**Comment by PrathikGopal** [comment] 2021-04-18 13:52
In my case it was an auth issue, i knew i messed up somewhere so i followed instructions again from first(didnt delete, just modified the files to what is needed in the build) and then this is the important part.
Disable skill to unlink account and then link account again in the alexa app.
Head over to test and type"open custom actions" - should respond as per the input text data

It works finally, didn't think it could be auth since it was already linked.

**Comment by Bodge-IT** [comment] 2021-04-27 09:33
I'm getting this issue too.  I have reviewed all the comments above and it's clear this error covers many problems.
In my Cloudwatch logs, I get no errors:

```
Timestamp
Message
No older events at this moment. 
Retry
2021-04-25T15:57:51.295+01:00	START RequestId: 99ffde78-0526-4070-876e-80b6e0d****** Version: 8
2021-04-25T15:57:51.384+01:00	[INFO] 2021-04-25T14:57:51.384Z 99ffde78-0526-4070-876e-80b6e0d****** Locale is en
2021-04-25T15:57:59.304+01:00	END RequestId: 99ffde78-0526-4070-876e-80b6e0d******
2021-04-25T15:57:59.304+01:00	REPORT RequestId: 99ffde78-0526-4070-876e-80b6e0d****** Duration: 8008.41 ms Billed Duration: 8000 ms Memory Size: 512 MB Max Memory Used: 62 MB Init Duration: 458.52 ms
2021-04-25T15:57:59.304+01:00	2021-04-25T14:57:59.303Z 99ffde78-0526-4070-876e-80b6e0d****** Task timed out after 8.01 seconds
```

- I'm not using account linking (my url has :8123 port with no "/")
- I am reseting my skill after every build to test
- I found a couple of typos in the lambda_function.py  (hanlder instead of handler) but these are called correctly so that not an issue.
- Language in skill UI is English(UK)
- My echos are set to use en-GB and are registered in UK.  
- I change the default ARN for AWS to eu-west1 (Ireland) for lambda and DynamoDB endpoints
- I did initially miss the input_text helper but have that in place now although "initial" is not available in GUI, so was not set
- I had also managed to copy over some of the Github copyright info into one of the files which was causing a problem but that also now fixed.
- I tried @rklueber suggestion of files outside of Lambda folder but that returns 'files not found' warning so I put mine back.
- @razorface1978 suggestion also didn't work for me
- - I also completely removed Alexa_Media integration and started again to make sure .co.uk selected and Auth worked.
I am now out of ideas, so any help would be appreciated.

**Comment by Bodge-IT** [comment] 2021-04-28 10:49
OK, I sorted my issue.  A simple one and nothing to do with any of @keatontaylor's work.  My issue was caused by a routing issue on my firewall.  This was causing intermittent and erratic connection problems on my HA url. 
My logs above said as much.  Note the last line highlighting a time-out.  Echo was also giving me a clue as it was taking forever trying to "Open custom actions" before getting the error this issue relates to. 
Now when I ask echo, the response is almost instant.

**Comment by DiegoCarrilho** [comment] 2021-09-25 15:15
My problems was the language on language_strings.json

2021-09-25T16:08:27.066+01:00 | KeyError: 'pt'

Fix: added my language to language_strings.json file.

**Comment by diaz66** [comment] 2022-01-07 17:40
> In Home Assistant, go to Developer Tools and select entity input_text.alexa_actionable_notification and check its state. It should be {"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}

Yes, I'm stoned, this was my problem. I have not included the input_text.yaml file on configuration.yaml.

 ! now ok.

**Closed** 2022-07-10 14:40 UTC
