### ISSUE TITLE
[Bug]: Event not firing

### ISSUE THREAD

**Issue by XcOM987** [keatontaylor/alexa-actions#210] opened 2023-09-23 15:44 UTC
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

francis@sutherland-mail.co.uk

### What happened?

I have followed the wiki and the youtube video, and I've gotten quite far, I've managed to configure the skill, and said skill has access to my Home Assistant instance and it can read the helper text entry without issue, I can change this manually and it will registerer in the skills test page, but I can't activate it from anywhere.

Steps undertaken so far:

- Alexa media player module setup (Historically installed, 4.7.2 installed)
- Custom data is set up in HA (Helper setup and can be accessed/updated)
- skill imported in AWS (Successful)
- invocation name changed (Successful)
- Skill built (Successful)
- Code updated with URL and long life token and deployed (Successful)
- HA configuration checked and reloaded (Successful)
- HA accessible from URL supplied in code (Successful)
- All instances (Skill, Phone, Account, HA) are set to EU

Symptoms/Diag:
- Skill call be called from the test window on Alexa Dev
- App is in Dev mode
- Can see the app in my Alexa app on my mobile device
- Skill is enabled in the app on my phone
- I've disabled and re-enabled the skill
- When using the trigger on my phone even typing it in (Open Custom Actions) the Alexa app doesn't register the skill is working
- Trying to trigger using the skill name has the same result
- When triggering the service call the helper updates but there is no response and no notification on my Alexa device
- I can control the Alexa devices from within HA including sending notifications)
- Tested with multiple Alexa devices from Echos, to Dots, to Shows, to the mobile app.
- Tested by setting the skill to use account linking rather than LLT and same results, I believe the skill can access my HA, but nothing can access the skill outside of the dev website.

I suspect this may be an issue with either Alexa not allowing the skill to be called outside the website dev environment, or something in the code not playing nice.

I've attached the logs but I don't think there of any use as there isn't anything in there indicating that any intent requests have been kicked off.
[log-events-viewer-result (1).csv](https://github.com/keatontaylor/alexa-actions/files/12706804/log-events-viewer-result.1.csv)

### Version

Latest

### What Alexa device are you using?

Echo

**Comment by DEADSEC-SECURITY** [comment] 2023-09-24 00:59
Did you respond to the alexa prompt?

**Comment by DEADSEC-SECURITY** [comment] 2023-09-24 00:59
Also if not already, activate debug mode and send me new logs.

**Comment by DEADSEC-SECURITY** [comment] 2023-09-24 01:02
With "I can't activate it from nowhere" do you mean sending a request to run the skill from HA? 

Did you install the required plugin for connecting HA to the alexa cloud? If yes, what plugin did you install? 

Send me the code/service_call in HA you're using to trigger the skill?

**Comment by XcOM987** [comment] 2023-09-24 08:30
Hiya,

Sorry, when I say "I can't activate it from nowhere", I meant to say I can't activate the new skill from anywhere other than the dev website.

If I try to access via my mobile app:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/3ffebe1f-89a6-49a3-b05a-5e8a389879bd)

If I access via the Dev console on the website:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/93bb1b03-99df-4bb9-95fa-3c0ae710e989)

I've enabled debug mode, made some calls from my mobile app and from the console, only the console requests appear to be in the logs.

Many thanks
[logs1.txt](https://github.com/keatontaylor/alexa-actions/files/12708104/logs1.txt)

**Comment by DEADSEC-SECURITY** [comment] 2023-09-24 22:52
Did you attempt to trigger the skill via HA? What steps did you do to do so via HA?

**Comment by XcOM987** [comment] 2023-09-29 13:35
If I add a suppress confirmation in to the data of true or false I don' get the error in the logs but it makes no difference.

I am leaning towards this being an issue with Alexa as I can't trigger the skill from any alexa directly or from my phone even though I can see the skill in the dev section of my app.

**Comment by DEADSEC-SECURITY** [comment] 2023-09-29 15:55
Are your alexa skill and alexa devices under the same account?

**Comment by XcOM987** [comment] 2023-09-29 16:07
Hi,

It looks to be, I can see the skill in my app:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/c45f12bf-91d5-4467-81f7-210d959ad3a6)

Along with the second one I made just to make sure I followed the steps correctly:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/f32c2838-b2b5-43b4-95fa-74ad75dedbf6)

 I believe I only have one account for Alexa, I checked my password manager and can only find one account, I can also invoke my smart home devices from the dev environment which is linked to my Alexa account.

**Comment by XcOM987** [comment] 2023-09-29 16:08
The only thing I can think of is I have to use US when creating the skill for the locale but I use Ireland/EU for where the skill runs from, which I believe is where my devices are located.

**Comment by DEADSEC-SECURITY** [comment] 2023-09-29 19:26
That wouldn't affect it. Just affects latency.

Are you sure that echo entity id is correct and refers to an alexa device? Also have you double checked that the id for the skill is correct? 

Did you configure alexa in home assistant using the library refered in docs?

**Comment by XcOM987** [comment] 2023-09-29 20:37
Prerequisites:

- Your Amazon developer Account is set up.
- - Account setup and running using same details
- - ![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/35da3f73-4b90-4f2e-af00-3ac0bfeb9c5a)

- The HACS Alexa Media Player integration is up and running.
- - HACS is installed and running, installed many addons via it historically.
- Your Home Assistant system is accessible from outside and you know the URL.
- - I have 2 URL's I can use, both work with the skill when triggering it from the dev console
- You decided for a language aka the local code of Alexa.
- - en-US as it's the only locale I can create the skill in but set the skill to run from Ireland/EU
- You created and loaded input_text.alexa_actionable_notification.
- - Helper is configured and can be accessed from the skill.
- - ![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/d0831b5a-599a-4422-98d1-105833dfb667)
- Long live token
- - A long live token is present and in use by the skill, the token is accepted as the skill can access the helper text entity from the dev console.
- Alexa Media Player installed
- Using correct Alexa entity
- - Script: ![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/c78ba429-5c7f-425e-9976-a906d6bd2de0)
- - Entity: ![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/639a3586-1dd9-424b-bc3e-23636f6ac77e)
- Skill ID correct?
- - Validated this is correct, also re-created the skill a second time to ensure and same results.

The skill seems to be communicting with my HA instance when being run from the dev environment:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/32daef33-3ee6-4bca-85ca-d6577cbde12e)
JSON output:
`{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>This is the helper entity, is this working correctly, yes or no??</speak>"
			},
			"reprompt": {
				"outputSpeech": {
					"type": "SSML",
					"ssml": "<speak></speak>"
				}
			},
			"shouldEndSession": false,
			"type": "_DEFAULT_RESPONSE"
		},
		"sessionAttributes": {},
		"userAgent": "ask-python/1.11.0 Python/3.7.17"
	}
}`

Happy to provide any info that might be needed

**Comment by ziggycatuk** [comment] 2023-10-15 14:22
I have this exact same issue..

Is there a fix ?

**Comment by IT-Fuzzi** [comment] 2023-10-17 20:49
I'm facing the same issue.
Everything works so far, except if I try to execute the 'service' via the developer tools. I don't see any event and nothing else happens.

My device is a Sonos One speaker with Alexa installed.

**Comment by DEADSEC-SECURITY** [comment] 2023-10-19 14:14
Can you try sending a message to you alexa device using the service notify.<ALEXA DEVICE> @XcOM987

**Comment by ziggycatuk** [comment] 2023-10-19 15:19
```
service: notify.alexa_media
data:
  data:
    type: tts
  message: "text to speech working "
  target:
    - media_player.lee_s_2nd_echo_dot
```

works absolutely fine.

**Comment by XcOM987** [comment] 2023-10-19 15:28
> Can you try sending a message to you alexa device using the service notify. @XcOM987

Yes, can send notifications using TTS without issue


> ```
> service: notify.alexa_media
> data:
>   data:
>     type: tts
>   message: "text to speech working "
>   target:
>     - media_player.living_room
> ```
> 
> works absolutely fine.

Yes, this works fine using the below
`service: notify.alexa_media
data:
  message: test
  target: media_player.living_room_echo_2
  data:
    type: tts
`

I can see the script is running because it's updating the helper entry:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/eb6d3b64-8aa1-458f-ab0a-ce076167c81d)

But the Alexa notification fails and doesn't respond
`service: script.activate_alexa_actionable_notification
data:
  text: "yes or no 19th oct 2023?"
  event_id: "Alexa_question_Test"
  alexa_device: media_player.living_room_echo_2
  `

Thanks everyone who's helped thus far, I'd really like to get this ironed out as it would be ground breaking for my needs

**Comment by XcOM987** [comment] 2023-10-19 15:44
> service: script.activate_alexa_actionable_notification data: text: "yes or no 19th oct 2023?" event_id: "Alexa_question_Test" alexa_device: media_player.living_room_echo_2

Oddly I rebuilt the skill with this new code and now it won't communicate with my home assistant instance
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/926ca529-ec3c-4c75-878f-73ccfc8994e0)

**Comment by ziggycatuk** [comment] 2023-10-19 15:56
I too have rebuilt the skill,  but nothing has changed.

I still receive the text reply from HA in the alexa dev console 

![alexa dev window](https://github.com/keatontaylor/alexa-actions/assets/110533007/c0b66dbb-838d-4727-b267-501ce2e3c37d)

but running the script in HA I just get silence

**Comment by DEADSEC-SECURITY** [comment] 2023-10-19 20:41
Have you tried triggering the skill with out using the script? Maybe is an issue with the script? @ziggycatuk

**Comment by DEADSEC-SECURITY** [comment] 2023-10-19 20:41
> > service: script.activate_alexa_actionable_notification data: text: "yes or no 19th oct 2023?" event_id: "Alexa_question_Test" alexa_device: media_player.living_room_echo_2
> 
> Oddly I rebuilt the skill with this new code and now it won't communicate with my home assistant instance ![image](https://user-images.githubusercontent.com/47461886/276673538-926ca529-ec3c-4c75-878f-73ccfc8994e0.png)

Check logs, activate debug mode

**Comment by DEADSEC-SECURITY** [comment] 2023-10-19 20:43
Also if you are trying master @XcOM987 update the requirements file with the one in master. It was a bug its fixed now

**Comment by ziggycatuk** [comment] 2023-10-19 21:01
> Have you tried triggering the skill with out using the script? Maybe is an issue with the script? 

if you mean like this, then still nothing. 

![dev tools1](https://github.com/keatontaylor/alexa-actions/assets/110533007/251a65f9-6ebd-44f9-b7bd-6397539ad232)

**Comment by XcOM987** [comment] 2023-10-20 11:52
Actions taken this morning:

Rebuilt the skill, and it failed building the code, looks like it pulled an old version for some reason, so I manually went through and pulled release [v0.10.1](https://github.com/keatontaylor/alexa-actions/releases/tag/v0.10.1) (N/B this is still referenced as 0.9.1 in the lambda_functions.py file.

I followed the guide and I can get the skill to reach my home assistant instance without issue, but only from within the development environments website but not from an Alexa device or phone:

Website:

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 12:07
Can you double check the account of the skill is the same as the echo devices? Did you install the skill in the mobile app? @XcOM987

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 12:07
@ziggycatuk can you double check the alexa skill too? Also do what I said in the last message to @XcOM987 too.

**Comment by XcOM987** [comment] 2023-10-20 12:09
> Can you double check the account of the skill is the same as the echo devices? Did you install the skill in the mobile app? @XcOM987

I can see the skill in my Alexa app:
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/3a667aca-3c02-4533-bbf3-e90c02c26ea0)
![image](https://github.com/keatontaylor/alexa-actions/assets/47461886/7c28c00e-116e-46db-b703-6cc5aa0aaf22)

I only have 1 Alexa account, but I have verified though that they are all using the same email address.

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 12:12
This is so weird. I'm honestly getting low on ideas.

**Comment by XcOM987** [comment] 2023-10-20 12:15
> This is so weird. I'm honestly getting low on ideas.

Yea, it's really strange, it's almost as if it's leaving my home-assistant but never reaching the Alexa environment, I am starting to lean to this being something outside of this project and something in the Aether

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 12:17
So lets recap @XcOM987 just to make sure I'm not lost.

- You can trigger the alexa device to talk using HA service right?
- You cannot trigger the skill from the HA services.
- If you go to dev tools in alexa developers your able to start the skill and confirm its making a connection with HA.

Given this behavior I would say no permission to execute skills? When you setup the alexa plugin for HA did you configure with the root account of you alexa? Can you try reinstalling the plugin and trying again? If you could activate logs of the plugin too in HA and send me the logs after attempting to call the skill I would appreciate.

For reference I'm using 

- Alexa Media Player 4.6.5
- HA 2023.9.0
- Supervisor 2023.10.0
- Operating System 10.5
- Frontend 20230906.1 - latest
- HACS 1.32.1

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 12:19
> > This is so weird. I'm honestly getting low on ideas.
> 
> Yea, it's really strange, it's almost as if it's leaving my home-assistant but never reaching the Alexa environment, I am starting to lean to this being something outside of this project and something in the Aether

Whats that Aether?

**Comment by XcOM987** [comment] 2023-10-20 12:23
Aeather is basically the void lol

Also I am currently reinstalling Alexa Media Player now to test that, I know I had issues in the past with authentication with it but that was long long ago

**Comment by ziggycatuk** [comment] 2023-10-20 12:27
> * You can trigger the alexa device to talk using HA service right? - **YES**
> * You cannot trigger the skill from the HA services. - **CORRECT**
> * If you go to dev tools in alexa developers your able to start the skill and confirm its making a connection with HA. - **YES**
> 
> 
> For reference I'm using
> 
> * Alexa Media Player 4.6.5 - **Running 4.7.7**
> * HA 2023.9.0 - **HA 2023.10.3**
> * Supervisor 2023.10.0 - **N/A running Docker**
> * Operating System 10.5 - **N/A running Docker**
> * Frontend 20230906.1 - latest - **Frontend 20231005.0 - latest**
> * HACS 1.32.1 - **1.33.0**
> 
> I'm also using Nabu Casa for connection and using direct connection instead of token

**Currently using duckdns.org with HA long lived token**

**Comment by ziggycatuk** [comment] 2023-10-20 12:29
Additionally ,  if I use the **media_player.play_media** service to call a routine that works fine

**Comment by XcOM987** [comment] 2023-10-20 12:47
> So lets recap @XcOM987 just to make sure I'm not lost.
> ......

>You can trigger the alexa device to talk using HA service right?
Correct, I can trigger Alexa via notify, play media, and is used in other automations.

>You cannot trigger the skill from the HA services.
Correct, I am unable to trigger the skill from within Home Assistant services or manually triggering the final stage of the script.

>If you go to dev tools in alexa developers your able to start the skill and confirm its making a connection with HA.
Correct, I can run the skill from the Alexa Developers page and it can read the input text helper.

As an aside, I can run custom triggers on Alexa devices, for example I have routines which will set alarms and timers on my alexa devices with routines (Via node red mind but still)

My setup:

- Alexa Media Player 4.7.7
- HA 2023.10.1
- Supervisor 2023.10.0
- Operating System 11.0
- Frontend 20231005.0 - latest
- HACS 1.33.0
- Access: Nabu Casa and direct URL with SSL (Both tested)

I reinstalled Alexa Media player, made no difference, I didn't see any options anywhere when setting it up referencing permissions or anything, but I double checked my details and all settings/options.

**Comment by ziggycatuk** [comment] 2023-10-20 12:58
I guess that's the only thing I've not tested

**Comment by XcOM987** [comment] 2023-10-20 12:58
The token login method for the Alexa Media Player?

**Comment by DEADSEC-SECURITY** [comment] 2023-10-20 13:01
also send me the logs of alexa media player. Make sure you put it in debug mode or activate them first.

**Comment by ziggycatuk** [comment] 2023-10-20 13:33
AMP log file;
[home-assistant_alexa_media_2023-10-20T13-29-03.943Z.log](https://github.com/keatontaylor/alexa-actions/files/13054783/home-assistant_alexa_media_2023-10-20T13-29-03.943Z.log)

**Comment by XcOM987** [comment] 2023-10-20 13:59
I will try without the token now, I did the first t

> also send me the logs of alexa media player. Make sure you put it in debug mode or activate them first.

I've sanitised the logs for you

[alexa logs.log](https://github.com/keatontaylor/alexa-actions/files/13055013/alexa.logs.log)

**Comment by ziggycatuk** [comment] 2023-10-20 14:39
> I setup a new skill and used account linking, same response, can access HA, but not trigger the skill from HA, wouldn't have anything to do with Locale will it? with HA being in en-GB and the skill being en-US?

I'm also UK based,  so maybe it is a regional thing

**Comment by ziggycatuk** [comment] 2023-10-20 16:11
> @IT-Fuzzi @ziggycatuk @XcOM987 if you guys use the following code: https://github.com/keatontaylor/alexa-actions/releases/tag/v0.8.2
> 
> Does it start working again?

No,  already tried that

**Comment by DEADSEC-SECURITY** [comment] 2023-10-22 01:37
> I will try without the token now, I did the first t
> 
> > also send me the logs of alexa media player. Make sure you put it in debug mode or activate them first.
> 
> I've sanitised the logs for you
> 
> [alexa logs.log](https://github.com/keatontaylor/alexa-actions/files/13055013/alexa.logs.log)
> 
> > Have you guys tried not using the token login method?
> 
> I setup a new skill and used account linking, same response, can access HA, but not trigger the skill from HA, wouldn't have anything to do with Locale will it? with HA being in en-GB and the skill being en-US?

miss match of local could be the issue

**Comment by DEADSEC-SECURITY** [comment] 2023-10-22 01:38
> > @IT-Fuzzi @ziggycatuk @XcOM987 if you guys use the following code: https://github.com/keatontaylor/alexa-actions/releases/tag/v0.8.2
> > Does it start working again?
> 
> I can confirm that it's working fine for me on a Sonos Player :-)
> 
> For me, the event listener got deactivated every time I clicked on to "Services" tab to trigger the service. Therefore, I was not able to see the event at all. Once it did it in two separate Chrome Tabs it was just working fine. Already in love with the extension, great work!
> 
> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/34891422/276985588-5d60430a-abe5-40e8-a1fd-ae7d4eb2262c.png">

what about master branch or version 0.10.1?

**Comment by XcOM987** [comment] 2023-10-22 08:36
> > > @IT-Fuzzi @ziggycatuk @XcOM987 if you guys use the following code: https://github.com/keatontaylor/alexa-actions/releases/tag/v0.8.2
> > > Does it start working again?
>........ 
> what about master branch or version 0.10.1?

Will test later on today and let you know, 0.10.1 was the version I was trying the other day, still leaning towards it being something in the void between HA and Alexa getting in the way given there's nothing in the logs to indicate it's rejected a request

**Comment by ziggycatuk** [comment] 2023-10-22 10:19
I have tried both and unfortunately neither worked for me.

**Comment by DEADSEC-SECURITY** [comment] 2023-10-22 14:02
Long shot, but could you try master branch? I bumped all libs to latest version.

**Comment by DEADSEC-SECURITY** [comment] 2023-10-22 15:38
have you guys tried downgrading the version of the home assistant alexa plugin to see if the error started with a recent  version?

**Comment by DEADSEC-SECURITY** [comment] 2023-10-22 15:48
Guys I just double checked your logs and seems like you guys are missing one parameter when making the call for the skill, which could explain the issue. Are you guys properly setting all the parameters?
Parameters required:
- `text`
- `event`
- `suppress_confirmation`

Make sure when you make the request you pass a valid value for each one of them

@XcOM987

**Comment by ziggycatuk** [comment] 2023-10-26 15:57
```
service: script.activate_alexa_actionable_notification
data:
  text: "Yes or no?"
  event_id: "alexa_actionable_notification_test"
  alexa_device: media_player.living_room
  suppress_confirmation: false
```

Still the same, no difference

**Comment by ziggycatuk** [comment] 2023-10-27 09:35
I've rebuilt this several times now.  The developer console works fine, but absolutely nothing when calling the skill from HA with no errors produced.

I've upgraded and downgraded Home Assistant and AMP ( AMP is running fine for notifications and running routines).

any other suggestions?

**Comment by ziggycatuk** [comment] 2023-10-30 09:51
@XcOM987 have you had any success getting this running ?

**Comment by XcOM987** [comment] 2023-10-30 11:26
> Guys I just double checked your logs and seems like you guys are missing one parameter when making the call for the skill, which could explain the issue. Are you guys properly setting all the parameters? Parameters required:
> 
> * `text`
> * `event`
> * `suppress_confirmation`
> 
> Make sure when you make the request you pass a valid value for each one of them
> 
> @XcOM987

If I add the Suppress_confirmation as true or false it makes no difference

**Comment by DEADSEC-SECURITY** [comment] 2023-10-30 12:23
what version are you guys running? Have you tried master?

**Comment by Hochstatter** [comment] 2023-11-18 23:09
I do have the very same issue after installing today the latest version strictly according to the installation guide.
Any ideas how this can be fixed?

**Comment by ziggycatuk** [comment] 2023-11-18 23:32
> I do have the very same issue after installing today the latest version strictly according to the installation guide. Any ideas how this can be fixed?

What region are you in?  myself and the OP are both in the UK and it appears it just does not work,  I've spent days on it.

I've Just given up now and accepted its broken

**Comment by Hochstatter** [comment] 2023-11-19 19:31
**I have the very same issue and found a workaround (see below).**

I am based in Germany and use EU (Ireland) as hosting region.

I can successfully test the skill both …
(A) … in the Alexa Simulator in the Developer Console, open the skill with its invocation name and it gives me the correct phrase.
(B) … via an echo by asking _“Alexa, open invocation name”_ and it also gives me the correct phrase.

The problem is that there is no reaction from the specified Alexa device when using the _script.activate_alexa_actionable_notification_. I tried with several echo devices but no success. (They are all just Echo Dots 2nd Generation but hopefully this should not be the issue.)

However, when I test the skill afterwards either (A) via the Alexa Simulator or (B) via the spoken request to Alexa, it answers in both cases with the new _“text”_ of the script. This proves to me that the Skill ID is correct. 
In the Developer Tools under Events I can even listen to the event _alexa_actionable_notification_ and can observe that the response contains the correct _event_id_, _event_response_ as well as _event_response_type_. This proves that the parameters are transferred to Alexa and that the skill is working (at least in theory).

Based on these findings, I build the **following WORKAROUND**:
First, I fire the _script.activate_alexa_actionable_notification_ in HA to send the parameters to Alexa (but as usual nothing happens). Afterwards, I delay for a few seconds and then fire an Alexa routine which starts the script by using the invocation name. 
I have to admit that it is a bit cumbersome but finally I got it working.

**Comment by ziggycatuk** [comment] 2023-11-19 20:07
This isn't the very same issue,

> **I have the very same issue and found a workaround (see below).**
> 
> I am based in Germany and use EU (Ireland) as hosting region.
> 
> I can successfully test the skill both … (A) … in the Alexa Simulator in the Developer Console, open the skill with its invocation name and it gives me the correct phrase. **(B) … via an echo by asking _“Alexa, open invocation name”_ and it also gives me the correct phrase.**

Your workaround unfortunately doesn't work for me as myself or the OP has never been able to get ANY response from an Echo device

**Comment by Whizzykid** [comment] 2023-12-04 20:25
Here to say I'm in the exact same position. UK Based, local EN US, Region EU.

Hopefully, we'll find a solution because I'm frustrated getting all the way through the read me to fall at the final hurdle. 

Thanks

**Comment by ziggycatuk** [comment] 2023-12-05 20:55
> Here to say I'm in the exact same position. UK Based, local EN US, Region EU.
> 
> Hopefully, we'll find a solution because I'm frustrated getting all the way through the read me to fall at the final hurdle.
> 
> Thanks

I wouldn't hold your breath,  it's very clear it no longer works for UK based accounts.

**Comment by DEADSEC-SECURITY** [comment] 2023-12-08 23:41
@Whizzykid try using UK instead of EN US

**Comment by xela1** [comment] 2023-12-09 10:46
> Here to say I'm in the exact same position. UK Based, local EN US, Region EU.
> 
> Hopefully, we'll find a solution because I'm frustrated getting all the way through the read me to fall at the final hurdle.
> 
> Thanks

I forked the repo a few months ago and added what was required to make it work in the UK, it's out of date now, but you should be able to see what I did - https://github.com/xela1/alexa-actions

I'll try and find some time today to bring it up to date and make a pull request to get the UK bits into the main repo

I believe it was deployed in EU with language UK

**Comment by xela1** [comment] 2023-12-09 11:54
I've recreated my repo with the up to date code, added the relevant locales for UK and created a pull request

If you want to test it before the PR is merged you can use https://github.com/keatontaylor/alexa-actions.git instead

During deployment I selected English (UK) and deployed to EU (Ireland)

**Comment by XcOM987** [comment] 2023-12-09 19:14
I've not had a great deal of spare time recently but I will have a go tomorrow

**Comment by ziggycatuk** [comment] 2023-12-09 20:50
@xela1 - thank you for taking the time to do this..  Hopefully I'll also have a go at getting this working tomorrow and report back.

cheers

**Comment by ziggycatuk** [comment] 2023-12-10 16:28
@xela1 -  you are a legend,  I'm happy to report this is now working :)

very much appreciated.  thank you

**Comment by DEADSEC-SECURITY** [comment] 2023-12-10 16:56
@xela1 thank you so much for the fix. Please feel free to open a PR and Ill merger it asap.

**Comment by xela1** [comment] 2023-12-10 18:43
> @xela1 thank you so much for the fix. Please feel free to open a PR and Ill merger it asap.

No worries, I meant to do it when I set mine up months ago, but you know what it's like, got it working then forgot all about it :)

I created #216 yesterday, just needs approving I think

**Closed** 2023-12-10 18:55 UTC
Labels: bug
